### PR TITLE
Yara process detection for Qakbot and Bazarbackdoor using Malpedia TL…

### PR DESCRIPTION
**Pull request by Hestat**
Yara process detection for Qakbot and Bazarbackdoor using Malpedia TLP White rules, tested as working on live malware samples on  5-5-2021.

### CODE REVIEW

**Comment by scudette** [comment]
These are very cool. But I wonder if we can make it more generic and reuse a lot of this code. It is very similar to Windows.Detection.ProcessMemory.CobaltStrike perhaps all those can be combined into the same artifact?

Also I would like to not include a lot of yara content inside the artifacts because it  just takes a lot of space and it is also hard to keep it up to date. Maybe we should include the yara rules in a separate repository as a tool within the artifact? This way we can version it and reuse it easily.  Perhaps it makes sense to just include all the commonly used yara rules in a single artifact so the artifact only does one pass on all the processes?

**Comment by Hestat** [comment]
Correct, these are indeed modeled directly off of the Cobalt Strike detection, which was kind of like magic the first time I used it. I'm watching the class on velociraptor this week and getting used to creating artifacts. These two specific malware families I targeted due to the way they inject into running processes making them harder to detect by normal means like process monitoring via sysmon, etc. I would though love to see an even wider capability for in memory detection, but not sure I've got a deep enough understanding of VQL to quite make that a reality yet.

**Comment by CR-OmerYampel** [comment]
I agree with @scudette , there's already generic YARA vql:

on disk:
https://github.com/Velocidex/velociraptor/blob/352fec8b9c285b57bb2cc12cb11dc1900f308921/artifacts/definitions/Windows/Detection/Yara/NTFS.yaml

in memory:
https://github.com/Velocidex/velociraptor/blob/352fec8b9c285b57bb2cc12cb11dc1900f308921/artifacts/definitions/Windows/Detection/RemoteYara/Process.yaml

That anyone that has vraptor can simply plug any yara rule into. If it goes down the road of having an artifact for the detection of every single malware its going to simply duplicate something like sigma

**Comment by scudette** [comment]
It would still be very convenient to have some library of curated yara rules that can be launched at the hit of a button :-). 

We could turn all the above artifacts into a single generic memory scanning artifact. If we put the rules in a github repository then we can version them and update with new rules as needed. Then the rules will be upgraded automatically with each VR release. When used, the rules will be downloaded to the EP automatically and we can scan for all malware types in one pass.

The trick is actually adapting the yara rules to use in memory (many rules in the wild do not make sense to run in memory since they have conditions like filesize or starting bytes). This is where curation is important.

**Comment by scudette** [comment]
Now that we have the Artifact Exchange up, this would be an excellent candidate for it. Perhaps resubmit it there?

**Pull request closed without merging**
