### PR TITLE
Include snaps in Linux.Debian.Packages artifact

### PR DESCRIPTION
**Pull request by misje**
Like it or not, the Canonical app store for Linux, snap, is included in Ubuntu (and possibly other Ubuntu-flavoured distros), and it can also be installed on other Debian systems. When looking for installed packages on a Debian system, it makes sense to also look for installed snaps. A number of software packages are distributed in both snap and deb formats.

The changes to the Linux.Debian.Packages artifact are summarised as follows:

- Add a new parameter for the snapd UNIX socket
- Add two new queries, and keep the original query mostly intact, now named "DebPackages". Changes to original query:
  - Use `humanize()` on "InstalledSize" instead of displaying bytes
  - Include package description as a new column, hidden by default: \_Description
- The new query "Snaps" lists all installed snaps, queried from the snap daemon (snapd) using a HTTP GET request to a UNIX socket. This is by far the easiest way to parse installed package details, avoiding having do deal with files in compressed SquashFS filesystems. If the snapd daemon does not respond, or if snapd is not installed, this query simply returns nothing.
- Add a third query that combines the deb and snap package lists, with a column "Type" that indicates the package type ("deb", "snap")

The golden test output has been updated, an example snapd JSON response is included, but there is currently no test logic to mock the HTTP call to output the contents of said JSON file.

How would I go about mocking http_client and simulate the response with the contents of artifacts/testdata/files/debian/snaps.json?

### CODE REVIEW

**Comment by scudette** [comment]
I changed the combined result to be a notebook query since there is no point having the client send the same data twice - we can just combine it in post processing. I also added a http_client mock and cleaned up the VQL a bit.

**Comment by misje** [comment]
Good changes, thanks. I didn't intend to mess up the original formatting, by the way. I've just ended up relying on the included formatter for all my VQL, even though it's not exactly perfect.

**Comment by predictiple** [comment]
This is a nice improvement. BUT there are some issues:

1. The notebook is associated with the Snaps source. If that source returns no data, which will be the case on systems not using Snap, then the notebook is inaccessible. Maybe it should be associated with the DebPackages source instead as that should be present on all systems?
2. In the notebook definition the source plugin refers to the sources explicitly by name, which means a custom/renamed version of the artifact won't be able to find it's sources.
3. The ColumnTypes definitions in VQL seem to be what's causing the behaviour discussed in #3605. Removing them results in the expected hidden behaviour. Declaring `column_types` in the yaml also results in the expected behaviour.

**Comment by misje** [comment]
Excellent points. I did in fact notice that I had to modify the notebook to make it run on a version earlier than master (i.e. prefix with "Custom"), but I didn't think too much about it.

Is a notebook suggestion an alternative?

**Comment by predictiple** [comment]
I'm not sure what the "recommended" way is to define a combined results notebook when you have multiple sources that may or may not return results. In general it could be the case that one of the sources will have results without being able to predict which one that will be. Maybe it's a design issue. Hopefully @scudette can advise.

The suggestion-type notebook won't change the situation because if the source has no data you won't be able to select the suggestion.

Notebooks have to belong to a source but `source()` -with no parameters- refers to only the data from that source. So other sources do have to be referred to by name which necessarily includes the artifact name, and that makes it brittle.

**Comment by scudette** [comment]
This is a good point - the behavior of only adding cells for artifacts that returned results is actually problematic in several cases - for example when the user clicks the notebook tab before the collection actually returned anything no cells will be shown. 

Perhaps we just always add the cells for all sources regardless of if any results are returned?

**Pull request merged**
