### PR TITLE
Added plist parser and MacOS.System.Users Artifact

### PR DESCRIPTION
**Pull request by scudette**
Example output:

```
{
  "Name": "mike",
  "RealName": "Mike Cohen",
  "UserShell": "/opt/local/bin/bash",
  "HomeDir": "/Users/mike",
  "AppleId": {
   "allows password reset": true,
   "linked identities": [
    {
     "anchor dn": "CN=Apple Root CA,OU=Apple Certification Authority,O=Apple Inc.,C=US",
     "full name": "mike@velocidex.com",
     "name": "com.apple.idms.appleid.prd.000682-...",
     "principal": "com.apple.idms.appleid.prd.000682-...",
     "subject dn": "CN=com.apple.idms.appleid.prd.000682-...",
     "timestamp": "2019-01-19T08:24:05Z"
    }
   ]
  },
  "CreationTime": "2019-01-19T08:21:48.928595066Z",
  "FailedLoginCount": 0,
  "FailedLoginTimestamp": null,
  "PasswordLastSetTime": "2019-01-19T08:21:50.771846055Z"
 },
```

### CODE REVIEW

**Comment by Uchedanieln** [comment]
- [ ] image

**Comment by Uchedanieln** [comment]
- [ ] Help

**Comment by scudette** [comment]
I'm not sure what you are saying here?

**Comment by Uchedanieln** [comment]
Optional []()

**Review by Uchedanieln — COMMENTED** [review]
Optional [approved]()

**Pull request merged**
