### PR TITLE
Parse Linux group IDs, names and memberships

### PR DESCRIPTION
**Pull request by misje**
I've had the need to look up group names from GIDs, as well as finding group memberships. This simple artifact does that. It is very much like Linux.Sys.Users, except that GID is an int. I felt that this made more sense, since gid in stat() is an int.

### CODE REVIEW

**Comment by misje** [comment]
I added a test, both for this artifact and Users. I suppose it would make sense for these two to be pretty similar. Should I rename "GID" to "Gid"? Use string instead of int for GID? I take it we don't modify Users in order to ensure backwards compatibility.

**Comment by scudette** [comment]
This test is failing because the files on windows have `\r\n` termination. We can either change the artifact to support both line endings or set the git attribute file to ensure the test files dont get converted to windows line ending?

**Comment by misje** [comment]
Which files end up with \r\n? I just checked passwd and group in git, and they're still \n.

The Windows test also failed before I added tests. I force-pushed today after rebasing to latest master before adding the tests.

**Comment by scudette** [comment]
When you git clone on windows it changes the files line ending. This causes the test to fail - you can see it in the test log output.

If you are sure these files will never have windows endings in the wild you can set these files to binary here
https://github.com/Velocidex/velociraptor/blob/master/.gitattributes

or create a .gitattribute file further down the tree

**Comment by misje** [comment]
I see what you mean now. These files would never have CR in Linux systems as far as I know, but it makes sense to support it nevertheless. For instance if the passwd/group file parameter is pointing to a file copied off a computer, possibly getting converted along the way.

**Pull request merged**
