### PR TITLE
Update gh actions build

### PR DESCRIPTION
**Pull request by scudette**

### CODE REVIEW

**Comment by predictiple** [comment]
Update gh actions build by scudette · Pull Request -1233 · Velocidex-velociraptor · GitHub - Brave_936

The change to ubuntu-latest means the build is not compatible with Ubuntu 18 and earlier, resulting in this error:
> ./velociraptor-v0.6.1-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./velociraptor-v0.6.1-linux-amd64)

**Comment by scudette** [comment]
yeah 16-04 is due for deprecation next week on github actions.

**Comment by predictiple** [comment]
I'm hitting the error on 18.04 though. Maybe that's what we should use for the build.

**Comment by scudette** [comment]
sure that makes sense. Can you please send a pr?

**Comment by predictiple** [comment]
Unfortunately not at the moment. I'm on very limited internet.

**Comment by scudette** [comment]
no worries - just afk. will submit later

**Comment by predictiple** [comment]
Thanks. It's working on my 18.04 server again.

**Pull request merged**
