### PR TITLE
Add/RunMRU final and working test cases

### PR DESCRIPTION
**Pull request by mgreen27**
test cases should be working.
Optimised output to align to tidy fields as default.
Moved grouped output to nondefault output.
Added mock test cases.

### CODE REVIEW

**Comment by mgreen27** [comment]
@scudette looks like my mru mock tests impacted other tests? 
Is there a way to make mocks limited scope?

**Comment by scudette** [comment]
Argh you are right! We used to create a new scope every time but for performance I changed it to copy  a global scope instead. This works most of the time because we do not dynamically add/remove plugins and functions (they are built into the binary and just initialize once).

Except when running mocks they **are** added because the mock replaces the original function. So in the specific case of the testsuite we **do** want to recreate the scope from scratch.

This is a bug in the testsuite :-). Stand by for a fix - you could just merge it to your PR.

**Comment by mgreen27** [comment]
sounds good :)

**Comment by scudette** [comment]
OK cool - i sent you a PR you just need to merge it and then I will merge this one

**Comment by scudette** [comment]
Thanks for persevering with this :-)

**Pull request merged**
