### PR TITLE
Support custom configs in Server.Utils.CreateMSI

### PR DESCRIPTION
**Pull request by predictiple**

### CODE REVIEW

**Comment by scudette** [comment]
Do we want to at least parse it as a yaml file? It might be good to verify it a bit like https://docs.velociraptor.app/artifact_references/pages/admin.client.updateclientconfig/

**Comment by predictiple** [comment]
That's actually necessary to allow for the situation described on Discord. If you don't parse it as YAML then it gets config-validated by repack(). So it's a bit of a loophole which allows the problem to be solved. :smile: 

"Expert mode" is how I like to see it. We could put a warning note in?

**Comment by scudette** [comment]
Yeah good point - the repack function already validates the config

**Comment by predictiple** [comment]
It is a good idea to have at least basic config validation.

**Pull request merged**
