### PR TITLE
remove users to include the system path

### PR DESCRIPTION
**Pull request by randomaccess3**
Replace users\* with ** to include both users and systemprofile paths
C:\Windows\System32\config\systemprofile\AppData\LocalLow\Microsoft\CryptnetUrlCache

### CODE REVIEW

**Comment by scudette** [comment]
This is not ideal because a ** here will be very slow as it has to traverse the entire filesystem

It is better to use the Windows.Sys.Users to get the users profile directory directly.

**Comment by randomaccess3** [comment]
Ok. I'll find the full paths 

It would likely be under the users path and under system32/config. 

Same locallow path onwards for both but I don't have the exact full paths atm

**Comment by mgreen27** [comment]
> Ok. I'll find the full paths
> 
> It would likely be under the users path and under system32/config.
> 
> Same locallow path onwards for both but I don't have the exact full paths atm

Just replace your glob with:
C:/{Users/*,Windows/*/config/systemprofile}/AppData/LocalLow/Microsoft/CryptnetUrlCache/MetaData/*

**Comment by randomaccess3** [comment]
Ok I'll test that out and then fix the request.

**Pull request merged**
