### PR TITLE
Adding support for Arm64 Musl

### PR DESCRIPTION
**Pull request by Mirio**
Hi,
Could you please add the support for Arm64 with MUSL?
I've already rebuilt local and it seems to work as expected.
Regards,

### CODE REVIEW

**Comment by scudette** [comment]
Are you sure the standard musl build will build a cross compiler for arm64? it seems unlikely? 

Are you building this on an arm64 vm or an intel vm?

**Comment by Mirio** [comment]
Hi [scudette](https://github.com/scudette),
Yep, you are right, I've tested on ARM64 VM and works but on x86_64 returns a lot of errors.
Do I need to change the GitHub action? Do you have some suggestions about it?
Regards,

**Comment by scudette** [comment]
Usually we use musl to build a fully static binary without linking to glibc which happens by default when building on Linux. When cross compiling though (i.e. building on a different platform) it normally does not link to glibc and will actually produce a fully static image. I know that when building a linux binary on windows, it actually runs on any glibc. I wonder if cross compiling for arm will work on all glibc versions?

The only difficulty is that we can not have cgo enabled - otherwise we need c compilers for arm64 on the amd64 platform (this is possible but I have no idea how to do it). If you change your target to disable cgo and build on an amd64 platform does it work on arm64?

Another option is to use an arm64 builder (which we do for production releases) but the github actions dont seem to offer one:

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners

We have started to distribute arm64 release binaries but we dont build on each commit like the other platforms. How important is it to have a CI download for each commit? Is it sufficient to have a no cgo binary - it just means it lacks some of the plugins like sqlite but it should be ok for testing. After all this is what the CI build is for - just testing.

**Comment by Mirio** [comment]
Hi [scudette](https://github.com/scudette),
Thanks for the clarification, for example in my case the ARM64 + Alpine is cheaper with a reduced attack vector than x64 + Glibc distros. That case is most likely used case in production.

> If you change your target to disable cgo and build on an amd64 platform does it work on arm64?

I can test it and return the results, I will keep you updated.

> How important is it to have a CI download for each commit? Is it sufficient to have a no cgo binary - it just means it lacks some of the plugins like sqlite but it should be ok for testing. After all this is what the CI build is for - just testing.

Yep probably better to have the arm64 support only for the release branches and hotfix too.
Thanks

**Comment by scudette** [comment]
I just remembered that we are cross compiling for linux arm64 here
https://github.com/Velocidex/velociraptor/blob/d4812383367affa29fae63440fdf88fea238eb31/.github/workflows/go.yml#L64C27-L64C37

so we do have a linux arm64 binary produced on each build already. I dont think it needs musl specifically because it is cross compiled - please file a bug if this binary does not work on your system.

**Pull request closed without merging**
