### PR TITLE
Adds in memory yara scan VQL function

### PR DESCRIPTION
**Pull request by CR-OmerYampel**
This adds the ability to scan a VQL variables value without having to read data from process/file:

```
LET rule1 <= "wide nocase ascii: foobar"

LET rule2 <= '      rule Hit {
        strings:
          $a = "this is my secret" wide nocase
          $b = "this is my secret" nocase
        condition:
          any of them
      }'

SELECT string_yara(rules=rule1, string="xyzfoobarxyz") FROM scope()
SELECT string_yara(rules=rule2, string="this is my secret") FROM scope()
```

image

### CODE REVIEW

**Comment by scudette** [comment]
How is that different/better than the current data accessor method?

The current data accessor can be used with every plugin that expects a file so it is more general.

**Comment by CR-OmerYampel** [comment]
Do you have an example of how that works? I can't see how I would do that with either of the existing yara plugins

**Comment by scudette** [comment]
Something like this:
```sql
LET MyString = 'A string with a secret'
LET Rules = '
rule X {
 strings: 
   $a = "secret" ascii nocase wide
 condition:
  any of them
}
'
SELECT * FROM yara(files=MyString, accessor='data', rules=Rules)

```

**Comment by CR-OmerYampel** [comment]
I had no idea this was possible, that solves that, awesome!

**Pull request closed without merging**
