### PR TITLE
Update interactive config wizard

### PR DESCRIPTION
**Pull request by scudette**
Use https://github.com/charmbracelet/huh instead of the deprecated github.com/AlecAivazis/survey.

Refactor the questions to make the process more streamlined.

### CODE REVIEW

**Comment by predictiple** [comment]
Shouldn't we be masking the passwords?

Screenshot from 2024-12-12 08-10-02

**Comment by scudette** [comment]
I was in two minds about it - if we mask it we might need to ask twice and compare. OTOH the plain text password is not stored and only displayed on the screen (and huh wipes the screen properly). 

Seeing this is a config generator it is probable that the password is already written down (it is the initial password anyway). Also passwords are only used for self signed deployments which are less secure. 

So for all these reasons I thought its probably better not to mask the password? Or maybe we can have it typed twice?

**Comment by predictiple** [comment]
Masking it is a bit silly. Your reasons make sense and personally I prefer it to not be masked or entered twice. So as long as it's not an accidental oversight it's no problem.

**Comment by scudette** [comment]
It is definitely different behavior than the previous code though. Lets add it in without masking now and see what the feedback is

**Pull request merged**
