### PR TITLE
Add Linux memory acquisition

### PR DESCRIPTION
**Pull request by Zawadidone**

### CODE REVIEW

**Comment by Zawadidone** [comment]
@scudette is the failed test part of the PR?

**Comment by scudette** [comment]
No I dont think the failure is related. 

I think this is probably best added to the artifact exchange? Would you mind adding it there?

**Comment by Zawadidone** [comment]
Yes I will do that.

**Comment by Zawadidone** [comment]
https://github.com/Velocidex/velociraptor-docs/pull/722

**Pull request closed without merging**
