### PR TITLE
Update Autoruns.yaml

### PR DESCRIPTION
**Pull request by mgreen27**
Add switch for hash collection "-h".

### CODE REVIEW

**Comment by scudette** [comment]
While we are changing this one can we remove it from a parameter and use an argv array? This will allow use to safely remove the required permissions so anyone can collect this one.

**Comment by mgreen27** [comment]
I usually use the standard artifact so can do this but I wonder if other people use the other features?

**Comment by scudette** [comment]
It can be easily modified if needed. Changing the flags as a parameter makes the output unstable as the columns and their orders depends on the artifact parameters. We need to try and avoid changing the data shape of each artifact as it breaks any downstream processing that depend on it.

**Comment by mgreen27** [comment]
ok submitted. I think the csv formatting in this tool probably breaks any downstream processing by itself :P

**Comment by scudette** [comment]
This seems to timeout because hashing makes it super slow - we might want to break out the -a flag into separate options so we can test a smaller set (it should also make the test faster).

**Pull request merged**
