### PR TITLE
Client metadata fields can now be indexed and searched.

### PR DESCRIPTION
**Pull request by scudette**
A new config option `defaults.indexed_client_metadata` can now specify a list of fields in the client metadata fields. When the admin sets these fields, Velociraptor will add the fields to the client search index. This means it is possible to now search on these custom fields in the search bar.

For example, say we add the field "dept" to signify a client's Department:

```yaml
defaults:
  indexed_client_metadata:
    - dept
```

Adding a client metadata field `dept` with value `engineering` will allow us to now search for the client using the verb `dept:engineering` in the GUI

### CODE REVIEW

**Comment by misje** [comment]
This is a very welcome improvement! I just tried the latest build, configured a field, added metadata and tried searching for it. I got no results. Do I need to do something in order to update the index when modifying indexed metadata?

**Comment by scudette** [comment]
If you already have metadata configured you should be able to see results in about 10 minutes or so. This is the default house keeping threads frequency I think.

**Comment by predictiple** [comment]
It should work immediately after restarting the service. When I tested it there was no delay but I don't have thousands of client records.
```sql
select client_id from clients(search="dept:engineering")
```

**Comment by misje** [comment]
I tested adding metadata using the web interface. I had a newline in the metadata field name, that was it. It's not the first time I've put newlines in either the field or the value thinking it would submit the form.

**Pull request merged**
