### PR TITLE
Set a standards-compliant HTTP User-Agent, including version number.

### PR DESCRIPTION
**Pull request by hillu**

### CODE REVIEW

**Comment by scudette** [comment]
Do you think leaking the version in the clear is a good move from an op-sec perspective?

**Comment by hillu** [comment]
Not sure if including the version number is that much worse than just telling whoever may be interested just the product name.

To be honest, I was mainly thinking about client/server communication.

For all other HTTP usage, we may as well not set a UA at all.

**Comment by hillu** [comment]
@scudette what do you think about leaving out the User-Agent altogether for "external" communication?

**Comment by scudette** [comment]
Happy to drop it completely and expose it though the http client plugin parameter

https://docs.velociraptor.app/vql_reference/plugin/http_client/

But probably if we dropped it now it would allow fingerprinting the version to identify newer clients?

Maybe we need to have it configurable?

**Comment by hillu** [comment]
> Happy to drop it completely and expose it though the http client plugin parameter

Done for `http_client` and `upload_webdav`

**Pull request merged**
