### PR TITLE
Create hash plugin

### PR DESCRIPTION
**Pull request by 0xThiebaut**
During the analysis of compromised hosts we have encountered the need of computing the hash of multiple files. We currently have to download all the files and compute the hashes locally. This PR introduces the "hash" plugin to allow analysts to match a file's hash against known malware databases such as VirusTotal.

The supported algorithms are the ones listed in the [`crypto`](https://golang.org/pkg/crypto/#Hash) package.

```bash
./velociraptor -c server.config.yaml query 'SELECT * FROM hash(filename="/home/user/Downloads/file.yaml",accessor="file",algorithm=["md5","sha256","sha1"])'
```

> ```json
> [
>  {
>   "MD5": "421aeb97b91abfdc1db47dfb23e7d147",
>   "SHA1": "41c009ddbaa56968e6ff8e2a705274424b3423a8",
>   "SHA256": "4e7cab143a984dca60e209f18b69c2e8e16195ee1898c3cee7354fde7a410a5a"
>  }
> ]
> ```

### CODE REVIEW

**Comment by 0xThiebaut** [comment]
Do not merge, an improvement is underway.

**Comment by 0xThiebaut** [comment]
Some plugins such as the `stat` plugin provide within the results the `FullPath` property. What are the guidelines concerning this as well as the naming conventions between the `filename` and `path` arguments which are both used in Velociraptor?

**Comment by scudette** [comment]
There is a hash function - is that different from this one?

https://github.com/Velocidex/velociraptor/blob/master/vql/functions/hash.go

**Comment by 0xThiebaut** [comment]
Should have seen this earlier 😄 
Well my implementation supports more algorithms (all Go’s native algorithms) but as there is already an implementation, I will modify this PR to improve the above mentioned function while keeping it backwards compatible.
I will tag you as soon as this is done, thanks for pointing it out!

**Comment by scudette** [comment]
No problems. If you are adding more algorithms, please add a parameter to allow selection of algorithms - we dont want to calculate too many hashes un-necessarily. If the user only wants SHA1 then they should be able to select only that one.

Perhaps a bool for each algorithm or a comma separated list of algos?

**Comment by scudette** [comment]
Ah sorry - just noticed your PR already does it! Great!

**Comment by 0xThiebaut** [comment]
I'll actually close this in the meanwhile as I won't have time to port this in the coming days.

**Pull request closed without merging**
