### PR TITLE
Added a deaddisk command to generate config

### PR DESCRIPTION
**Pull request by scudette**
This allows to easily build templates for dead disk analysis.

To test mount a vmdk drive using "flat" mode (this is equivalent to a
dd image):

```
sudo vmware-mount -f /vmware_image.vmdk /tmp/deaddisk/
```

This will create a flat image at /tmp/deaddisk/flat

Now we have Velociraptor analyse the drive and produce a configuration
file.

```
velociraptor deaddisk --add_windows_disk /tmp/partitions/flat /tmp/out.config.yaml
```

Will generate a config file - current this automatically:
- Parses the partition table and find the windows OS partition
- Mounts the partition on C: using the ntfs parser - this will be
  available both using the "ntfs" accessor and "file" accessor in VQL

- Some initial registry hives are also mapped using the raw registry
  accessor. In VQL this is available using the "registry" accessor.
- Permissions are adjusted to prevent analysis leaking onto the
  analysis host.
- The info() plugin is mocked to impersonate a windows machine - this
  is required to pass precondition checks in most artifacts.

The overall result is that now collecting a windows artifact just
works:

```
velociraptor --config /tmp/out.config.yaml -v artifacts collect Windows.Forensics.Prefetch
```

### CODE REVIEW

**Comment by obvivdo** [comment]
Does this imply VR is able to do dead disk forensics on flat/raw files  ?

**Comment by scudette** [comment]
Yes this feature is in development - you can test with the latest CI build and provide feedback :-).

**Comment by bcvilnrotter** [comment]
I’m not sure if this is an implied feature (since I don’t think it is in any documentation), but I have never gotten this remapping feature to work on the windows binary, in a windows environment, on a flat raw image.

should this feature work, or is this feature still being built out?

**Comment by scudette** [comment]
It should work. If it does not please file a bug report (and use the latest release which at this time it's 0.6.5-2)

**Pull request merged**
